services:
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      - POSTGRES_USER=odegaa
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=practice-project
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U odegaa -d practice-project"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: practice-project
    ports:
      - "8083:8083"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/practice-project
      - SPRING_DATASOURCE_USERNAME=odegaa
      - SPRING_DATASOURCE_PASSWORD=admin